--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/VennDev/VPickaxe
build-by-default: true
branches:
- main
projects:
  VPickaxe:
    lint:
      phpstan: false
      syntaxError: false
    path: ""
...
